/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#c3c0ff',
        'on-secondary-fixed-variant': '#404758',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#351000',
        'surface-container-highest': '#e1e3e4',
        'tertiary-fixed-dim': '#ffb695',
        'inverse-surface': '#2e3132',
        'surface-dim': '#d9dadb',
        'on-secondary-container': '#5c6274',
        'on-surface-variant': '#464555',
        'tertiary': '#7e3000',
        'on-background': '#191c1d',
        'outline': '#777587',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'tertiary-container': '#a44100',
        'secondary-container': '#d9dff5',
        'surface-container-high': '#e7e8e9',
        'tertiary-fixed': '#ffdbcc',
        'on-surface': '#191c1d',
        'primary-fixed': '#e2dfff',
        'surface': '#f8f9fa',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        'background': '#f8f9fa',
        'primary': '#3525cd',
        'secondary-fixed-dim': '#c0c6db',
        'outline-variant': '#c7c4d8',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed': '#0f0069',
        'on-primary-container': '#dad7ff',
        'primary-container': '#4f46e5',
        'secondary-fixed': '#dce2f7',
        'on-secondary-fixed': '#141b2b',
        'surface-tint': '#4d44e3',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e3e4',
        'surface-container': '#edeeef',
        'on-tertiary-container': '#ffd2be',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'secondary': '#575e70',
        'surface-container-low': '#f3f4f5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        'header-height': '48px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        'panel-width': '280px',
        base: '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        'table-cell': ['Inter', 'sans-serif'],
        'label-mono': ['Space Grotesk', 'sans-serif'],
        'body-main': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        h1: ['18px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'table-cell': ['13px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'label-mono': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-main': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
