"""add unique constraint on tasks org_id+number

Revision ID: 3263943a1511
Revises: 6935116194f1
Create Date: 2026-04-21 13:28:38.693290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3263943a1511'
down_revision: Union[str, Sequence[str], None] = '6935116194f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tasks_org_number', 'tasks', ['org_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tasks_org_number', 'tasks', type_='unique')
    # ### end Alembic commands ###
