"""add agents and relationships

Revision ID: 7f3f75af735f
Revises: abc33e9b5d55
Create Date: 2026-04-21 12:00:41.733700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f3f75af735f'
down_revision: Union[str, Sequence[str], None] = 'abc33e9b5d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('human', 'ai', name='agenttype'), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=True),
    sa.Column('connector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('authority_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=False),
    sa.Column('to_agent_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('reports_to', 'collaborates_with', name='relationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_agent_id', 'to_agent_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_relationships')
    op.drop_table('agents')
    # ### end Alembic commands ###
